name: caller-workflow
on: [workflow_dispatch]
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      Environment: 'Development'
      NodeVersion: '18'
    # You can add more secrets as needed