name: Context Example

on: [push]  

jobs:
    my-Context:
        runs-on: ubuntu-latest
        steps:
            - name: Print context information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Repository: ${{ github.repository }}"
                echo "Hello Action:, $GITHUB_ACTION"
              env:
                GITHUB_ACTION: ${{ github.action }}
                