name: dependent.yml

on: [push]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:

            - name: Run job1
              run: echo "Running job1"
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:

            - name: Run job2
              run: echo "Running job2 after job1"