name: workflow

on: ['push', 'pull_request']

jobs:
    set-env:
        runs-on: ubuntu-latest
        steps:
            - name: Set up environment variables
              run: |
                echo "ACTION_ENV=Production" >> $GITHUB_ENV
    addTo-Systempath:
        runs-on: ubuntu-latest
        needs: set-env
        steps:
            - name: Add to system path
              run: |
                echo "PATH=$PATH:/usr/local/binsss" >> $GITHUB_PATH
    print-env:
        runs-on: ubuntu-latest
        needs: addTo-Systempath
        steps:
            - name: Print environment variables
              run: |
                echo "GITHUB_PATH is $GITHUB_PATH"
            - name: Failed-On-Error
              run: |
                echo "::Error:: This step will fail if the previous step fails."

    set-output:
        runs-on: ubuntu-latest
        needs: print-env
        steps:
            - name: Set output variable
              id: set_output
              run: |
                echo "output_var=Hello, World!" >> $GITHUB_OUTPUT
            - name: Print output variable
              run: |
                echo "Output variable is ${{ steps.set_output.outputs.output_var }}"
  
    create-debugmsg:
        runs-on: ubuntu-latest
        steps:
            - name: Create debug message
              run: |
                echo "::debug:: This is a debug message for the workflow."