name: Build Script Workflow

on:
  workflow_dispatch:
env:
  PROJECT_NAME: SampleApp
  PROJECT_ENV: production

jobs:
    script-to-be-run:
        runs-on: ubuntu-latest
        steps:
            
            - name: ${PROJECT_NAME} Build Step
              run: |
                echo "🔧 Building $PROJECT_NAME in $PROJECT_ENV mode"
                echo "ℹ️ Workflow Triggered by $GITHUB_ACTOR"
                echo "📅 Date: $(date)"
            - name: Step with Local Variables
              env:
                PROJECT_NAME: SampleApp2
                PROJECT_Version: v1.0.0
              run: |
                echo "Running script with local variables"
                echo "Project Name: $PROJECT_NAME"
                echo "Project Environment: $PROJECT_Version"