name: secret
on: ['push', 'pull_request']

jobs:
    secret:
        env:
            API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        runs-on: ubuntu-latest
        steps:

        - name: Run secret script
          run: | 
            echo "${API_KEY}"
            echo "::add-mask::$API_KEY"
            